# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(764, 800)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.centralWidget = QWidget(MainWindow)
        self.centralWidget.setObjectName(u"centralWidget")
        self.zitai = QFrame(self.centralWidget)
        self.zitai.setObjectName(u"zitai")
        self.zitai.setGeometry(QRect(30, 50, 321, 281))
        self.zitai.setFrameShape(QFrame.StyledPanel)
        self.zitai.setFrameShadow(QFrame.Raised)
        self.layoutWidget = QWidget(self.zitai)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(12, 12, 271, 201))
        self.gridLayout = QGridLayout(self.layoutWidget)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.du_4 = QLabel(self.layoutWidget)
        self.du_4.setObjectName(u"du_4")
        font = QFont()
        font.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1")
        font.setPointSize(20)
        self.du_4.setFont(font)

        self.gridLayout.addWidget(self.du_4, 2, 3, 1, 1)

        self.Yaw = QLabel(self.layoutWidget)
        self.Yaw.setObjectName(u"Yaw")
        self.Yaw.setFont(font)

        self.gridLayout.addWidget(self.Yaw, 0, 0, 1, 1)

        self.mi = QLabel(self.layoutWidget)
        self.mi.setObjectName(u"mi")
        self.mi.setMaximumSize(QSize(16777215, 16777215))
        self.mi.setFont(font)

        self.gridLayout.addWidget(self.mi, 3, 3, 1, 1)

        self.Yaw_s = QLabel(self.layoutWidget)
        self.Yaw_s.setObjectName(u"Yaw_s")
        self.Yaw_s.setFont(font)

        self.gridLayout.addWidget(self.Yaw_s, 0, 1, 1, 2)

        self.Roll = QLabel(self.layoutWidget)
        self.Roll.setObjectName(u"Roll")
        self.Roll.setFont(font)

        self.gridLayout.addWidget(self.Roll, 1, 0, 1, 1)

        self.du_2 = QLabel(self.layoutWidget)
        self.du_2.setObjectName(u"du_2")
        self.du_2.setFont(font)

        self.gridLayout.addWidget(self.du_2, 0, 3, 1, 1)

        self.Roll_s = QLabel(self.layoutWidget)
        self.Roll_s.setObjectName(u"Roll_s")
        self.Roll_s.setFont(font)

        self.gridLayout.addWidget(self.Roll_s, 1, 1, 1, 2)

        self.Pitch = QLabel(self.layoutWidget)
        self.Pitch.setObjectName(u"Pitch")
        self.Pitch.setFont(font)

        self.gridLayout.addWidget(self.Pitch, 2, 0, 1, 1)

        self.Pitch_s = QLabel(self.layoutWidget)
        self.Pitch_s.setObjectName(u"Pitch_s")
        self.Pitch_s.setFont(font)

        self.gridLayout.addWidget(self.Pitch_s, 2, 1, 1, 2)

        self.du_3 = QLabel(self.layoutWidget)
        self.du_3.setObjectName(u"du_3")
        self.du_3.setFont(font)

        self.gridLayout.addWidget(self.du_3, 1, 3, 1, 1)

        self.Depth = QLabel(self.layoutWidget)
        self.Depth.setObjectName(u"Depth")
        self.Depth.setMaximumSize(QSize(16777215, 16777215))
        self.Depth.setFont(font)

        self.gridLayout.addWidget(self.Depth, 3, 0, 1, 1)

        self.Depth_s = QLabel(self.layoutWidget)
        self.Depth_s.setObjectName(u"Depth_s")
        self.Depth_s.setMaximumSize(QSize(16777215, 16777215))
        self.Depth_s.setFont(font)

        self.gridLayout.addWidget(self.Depth_s, 3, 1, 1, 2)

        self.zhuangtai = QFrame(self.centralWidget)
        self.zhuangtai.setObjectName(u"zhuangtai")
        self.zhuangtai.setGeometry(QRect(360, 50, 131, 51))
        self.zhuangtai.setFrameShape(QFrame.StyledPanel)
        self.zhuangtai.setFrameShadow(QFrame.Raised)
        self.Led_gps = QLabel(self.zhuangtai)
        self.Led_gps.setObjectName(u"Led_gps")
        self.Led_gps.setGeometry(QRect(10, 30, 51, 16))
        self.Led_star = QLabel(self.zhuangtai)
        self.Led_star.setObjectName(u"Led_star")
        self.Led_star.setGeometry(QRect(10, 10, 51, 16))
        self.Led_star_s = QLabel(self.zhuangtai)
        self.Led_star_s.setObjectName(u"Led_star_s")
        self.Led_star_s.setGeometry(QRect(70, 10, 41, 16))
        self.Led_gps_s = QLabel(self.zhuangtai)
        self.Led_gps_s.setObjectName(u"Led_gps_s")
        self.Led_gps_s.setGeometry(QRect(70, 30, 41, 16))
        self.control = QFrame(self.centralWidget)
        self.control.setObjectName(u"control")
        self.control.setGeometry(QRect(360, 110, 271, 291))
        self.control.setFrameShape(QFrame.StyledPanel)
        self.control.setFrameShadow(QFrame.Raised)
        self.left_w = QLabel(self.control)
        self.left_w.setObjectName(u"left_w")
        self.left_w.setGeometry(QRect(10, 30, 51, 16))
        self.left_a = QLabel(self.control)
        self.left_a.setObjectName(u"left_a")
        self.left_a.setGeometry(QRect(10, 10, 51, 16))
        self.left_p = QLabel(self.control)
        self.left_p.setObjectName(u"left_p")
        self.left_p.setGeometry(QRect(10, 50, 51, 16))
        self.left_a_s = QLineEdit(self.control)
        self.left_a_s.setObjectName(u"left_a_s")
        self.left_a_s.setGeometry(QRect(60, 10, 41, 16))
        self.left_w_s = QLineEdit(self.control)
        self.left_w_s.setObjectName(u"left_w_s")
        self.left_w_s.setGeometry(QRect(60, 30, 41, 16))
        self.left_p_s = QLineEdit(self.control)
        self.left_p_s.setObjectName(u"left_p_s")
        self.left_p_s.setGeometry(QRect(60, 50, 41, 16))
        self.left_w_2 = QLabel(self.control)
        self.left_w_2.setObjectName(u"left_w_2")
        self.left_w_2.setGeometry(QRect(10, 110, 51, 16))
        self.left_p_2 = QLabel(self.control)
        self.left_p_2.setObjectName(u"left_p_2")
        self.left_p_2.setGeometry(QRect(10, 130, 51, 16))
        self.right_p_s = QLineEdit(self.control)
        self.right_p_s.setObjectName(u"right_p_s")
        self.right_p_s.setGeometry(QRect(60, 130, 41, 16))
        self.left_a_2 = QLabel(self.control)
        self.left_a_2.setObjectName(u"left_a_2")
        self.left_a_2.setGeometry(QRect(10, 90, 51, 16))
        self.right_a_s = QLineEdit(self.control)
        self.right_a_s.setObjectName(u"right_a_s")
        self.right_a_s.setGeometry(QRect(60, 90, 41, 16))
        self.right_w_s = QLineEdit(self.control)
        self.right_w_s.setObjectName(u"right_w_s")
        self.right_w_s.setGeometry(QRect(60, 110, 41, 16))
        self.rightr_p = QLabel(self.control)
        self.rightr_p.setObjectName(u"rightr_p")
        self.rightr_p.setGeometry(QRect(140, 130, 51, 16))
        self.rightr_a_s = QLineEdit(self.control)
        self.rightr_a_s.setObjectName(u"rightr_a_s")
        self.rightr_a_s.setGeometry(QRect(190, 90, 41, 16))
        self.rightr_p_s = QLineEdit(self.control)
        self.rightr_p_s.setObjectName(u"rightr_p_s")
        self.rightr_p_s.setGeometry(QRect(190, 130, 41, 16))
        self.rightr_w_s = QLineEdit(self.control)
        self.rightr_w_s.setObjectName(u"rightr_w_s")
        self.rightr_w_s.setGeometry(QRect(190, 110, 41, 16))
        self.rightr_w = QLabel(self.control)
        self.rightr_w.setObjectName(u"rightr_w")
        self.rightr_w.setGeometry(QRect(140, 110, 51, 16))
        self.rightr_a = QLabel(self.control)
        self.rightr_a.setObjectName(u"rightr_a")
        self.rightr_a.setGeometry(QRect(140, 90, 51, 16))
        self.leftr_w = QLabel(self.control)
        self.leftr_w.setObjectName(u"leftr_w")
        self.leftr_w.setGeometry(QRect(140, 30, 51, 16))
        self.leftr_p = QLabel(self.control)
        self.leftr_p.setObjectName(u"leftr_p")
        self.leftr_p.setGeometry(QRect(140, 50, 51, 16))
        self.leftr_p_s = QLineEdit(self.control)
        self.leftr_p_s.setObjectName(u"leftr_p_s")
        self.leftr_p_s.setGeometry(QRect(190, 50, 41, 16))
        self.leftr_a = QLabel(self.control)
        self.leftr_a.setObjectName(u"leftr_a")
        self.leftr_a.setGeometry(QRect(140, 10, 51, 16))
        self.leftr_a_s = QLineEdit(self.control)
        self.leftr_a_s.setObjectName(u"leftr_a_s")
        self.leftr_a_s.setGeometry(QRect(190, 10, 41, 16))
        self.leftr_w_s = QLineEdit(self.control)
        self.leftr_w_s.setObjectName(u"leftr_w_s")
        self.leftr_w_s.setGeometry(QRect(190, 30, 41, 16))
        self.rightt_a = QLabel(self.control)
        self.rightt_a.setObjectName(u"rightt_a")
        self.rightt_a.setGeometry(QRect(140, 180, 51, 16))
        self.rightt_a_s = QLineEdit(self.control)
        self.rightt_a_s.setObjectName(u"rightt_a_s")
        self.rightt_a_s.setGeometry(QRect(190, 180, 41, 16))
        self.leftt_a_s = QLineEdit(self.control)
        self.leftt_a_s.setObjectName(u"leftt_a_s")
        self.leftt_a_s.setGeometry(QRect(60, 180, 41, 16))
        self.leftt_a = QLabel(self.control)
        self.leftt_a.setObjectName(u"leftt_a")
        self.leftt_a.setGeometry(QRect(10, 180, 51, 16))
        self.back_a_s = QLineEdit(self.control)
        self.back_a_s.setObjectName(u"back_a_s")
        self.back_a_s.setGeometry(QRect(60, 200, 41, 16))
        self.back = QLabel(self.control)
        self.back.setObjectName(u"back")
        self.back.setGeometry(QRect(10, 200, 51, 16))
        self.du_7 = QLabel(self.control)
        self.du_7.setObjectName(u"du_7")
        self.du_7.setGeometry(QRect(110, 10, 21, 16))
        self.Hz = QLabel(self.control)
        self.Hz.setObjectName(u"Hz")
        self.Hz.setGeometry(QRect(110, 30, 21, 16))
        self.du_9 = QLabel(self.control)
        self.du_9.setObjectName(u"du_9")
        self.du_9.setGeometry(QRect(110, 50, 21, 16))
        self.Hz_2 = QLabel(self.control)
        self.Hz_2.setObjectName(u"Hz_2")
        self.Hz_2.setGeometry(QRect(110, 110, 21, 16))
        self.du_8 = QLabel(self.control)
        self.du_8.setObjectName(u"du_8")
        self.du_8.setGeometry(QRect(110, 90, 21, 16))
        self.du_10 = QLabel(self.control)
        self.du_10.setObjectName(u"du_10")
        self.du_10.setGeometry(QRect(110, 130, 21, 16))
        self.du_11 = QLabel(self.control)
        self.du_11.setObjectName(u"du_11")
        self.du_11.setGeometry(QRect(240, 90, 21, 16))
        self.du_12 = QLabel(self.control)
        self.du_12.setObjectName(u"du_12")
        self.du_12.setGeometry(QRect(240, 130, 21, 16))
        self.Hz_3 = QLabel(self.control)
        self.Hz_3.setObjectName(u"Hz_3")
        self.Hz_3.setGeometry(QRect(240, 110, 21, 16))
        self.du_15 = QLabel(self.control)
        self.du_15.setObjectName(u"du_15")
        self.du_15.setGeometry(QRect(110, 180, 21, 16))
        self.du_16 = QLabel(self.control)
        self.du_16.setObjectName(u"du_16")
        self.du_16.setGeometry(QRect(240, 180, 21, 16))
        self.du_17 = QLabel(self.control)
        self.du_17.setObjectName(u"du_17")
        self.du_17.setGeometry(QRect(110, 200, 21, 16))
        self.du_13 = QLabel(self.control)
        self.du_13.setObjectName(u"du_13")
        self.du_13.setGeometry(QRect(240, 50, 21, 16))
        self.du_14 = QLabel(self.control)
        self.du_14.setObjectName(u"du_14")
        self.du_14.setGeometry(QRect(240, 10, 21, 16))
        self.Hz_4 = QLabel(self.control)
        self.Hz_4.setObjectName(u"Hz_4")
        self.Hz_4.setGeometry(QRect(240, 30, 21, 16))
        self.run_no = QLabel(self.control)
        self.run_no.setObjectName(u"run_no")
        self.run_no.setGeometry(QRect(140, 200, 51, 16))
        self.run_no_s = QLineEdit(self.control)
        self.run_no_s.setObjectName(u"run_no_s")
        self.run_no_s.setGeometry(QRect(190, 200, 41, 16))
        self.Led_gps_2 = QLabel(self.control)
        self.Led_gps_2.setObjectName(u"Led_gps_2")
        self.Led_gps_2.setGeometry(QRect(140, 230, 51, 16))
        self.Led_forward = QLabel(self.control)
        self.Led_forward.setObjectName(u"Led_forward")
        self.Led_forward.setGeometry(QRect(10, 230, 81, 16))
        self.Led_star_s_2 = QLineEdit(self.control)
        self.Led_star_s_2.setObjectName(u"Led_star_s_2")
        self.Led_star_s_2.setGeometry(QRect(90, 230, 31, 16))
        self.Led_gps_s_2 = QLineEdit(self.control)
        self.Led_gps_s_2.setObjectName(u"Led_gps_s_2")
        self.Led_gps_s_2.setGeometry(QRect(200, 230, 31, 16))
        self.left_k = QLabel(self.control)
        self.left_k.setObjectName(u"left_k")
        self.left_k.setGeometry(QRect(10, 70, 51, 16))
        self.left_k_s = QLineEdit(self.control)
        self.left_k_s.setObjectName(u"left_k_s")
        self.left_k_s.setGeometry(QRect(60, 70, 41, 16))
        self.du_18 = QLabel(self.control)
        self.du_18.setObjectName(u"du_18")
        self.du_18.setGeometry(QRect(110, 70, 21, 16))
        self.du_19 = QLabel(self.control)
        self.du_19.setObjectName(u"du_19")
        self.du_19.setGeometry(QRect(240, 70, 21, 16))
        self.leftr_k_s = QLineEdit(self.control)
        self.leftr_k_s.setObjectName(u"leftr_k_s")
        self.leftr_k_s.setGeometry(QRect(190, 70, 41, 16))
        self.leftr_k = QLabel(self.control)
        self.leftr_k.setObjectName(u"leftr_k")
        self.leftr_k.setGeometry(QRect(140, 70, 51, 16))
        self.du_20 = QLabel(self.control)
        self.du_20.setObjectName(u"du_20")
        self.du_20.setGeometry(QRect(110, 150, 21, 16))
        self.rightr_k_s = QLineEdit(self.control)
        self.rightr_k_s.setObjectName(u"rightr_k_s")
        self.rightr_k_s.setGeometry(QRect(190, 150, 41, 16))
        self.rightr_k = QLabel(self.control)
        self.rightr_k.setObjectName(u"rightr_k")
        self.rightr_k.setGeometry(QRect(140, 150, 51, 16))
        self.du_21 = QLabel(self.control)
        self.du_21.setObjectName(u"du_21")
        self.du_21.setGeometry(QRect(240, 150, 21, 16))
        self.right_k_s = QLineEdit(self.control)
        self.right_k_s.setObjectName(u"right_k_s")
        self.right_k_s.setGeometry(QRect(60, 150, 41, 16))
        self.left_p_3 = QLabel(self.control)
        self.left_p_3.setObjectName(u"left_p_3")
        self.left_p_3.setGeometry(QRect(10, 150, 51, 16))
        self.layoutWidget1 = QWidget(self.control)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(40, 260, 191, 25))
        self.horizontalLayout = QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.pushButton_2 = QPushButton(self.layoutWidget1)
        self.pushButton_2.setObjectName(u"pushButton_2")

        self.horizontalLayout.addWidget(self.pushButton_2)

        self.pushButton = QPushButton(self.layoutWidget1)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout.addWidget(self.pushButton)

        self.control_3 = QFrame(self.centralWidget)
        self.control_3.setObjectName(u"control_3")
        self.control_3.setGeometry(QRect(30, 340, 271, 101))
        self.control_3.setFrameShape(QFrame.StyledPanel)
        self.control_3.setFrameShadow(QFrame.Raised)
        self.left_w_5 = QLabel(self.control_3)
        self.left_w_5.setObjectName(u"left_w_5")
        self.left_w_5.setGeometry(QRect(10, 50, 51, 16))
        self.left_a_5 = QLabel(self.control_3)
        self.left_a_5.setObjectName(u"left_a_5")
        self.left_a_5.setGeometry(QRect(10, 30, 51, 16))
        self.yaw_desire = QLineEdit(self.control_3)
        self.yaw_desire.setObjectName(u"yaw_desire")
        self.yaw_desire.setGeometry(QRect(60, 30, 41, 16))
        self.roll_desire = QLineEdit(self.control_3)
        self.roll_desire.setObjectName(u"roll_desire")
        self.roll_desire.setGeometry(QRect(60, 50, 41, 16))
        self.leftr_w_3 = QLabel(self.control_3)
        self.leftr_w_3.setObjectName(u"leftr_w_3")
        self.leftr_w_3.setGeometry(QRect(140, 50, 51, 16))
        self.leftr_a_3 = QLabel(self.control_3)
        self.leftr_a_3.setObjectName(u"leftr_a_3")
        self.leftr_a_3.setGeometry(QRect(140, 30, 51, 16))
        self.pitch_desire = QLineEdit(self.control_3)
        self.pitch_desire.setObjectName(u"pitch_desire")
        self.pitch_desire.setGeometry(QRect(200, 30, 41, 16))
        self.run_or_on_pid = QLineEdit(self.control_3)
        self.run_or_on_pid.setObjectName(u"run_or_on_pid")
        self.run_or_on_pid.setGeometry(QRect(200, 50, 41, 16))
        self.du_37 = QLabel(self.control_3)
        self.du_37.setObjectName(u"du_37")
        self.du_37.setGeometry(QRect(110, 30, 21, 16))
        self.Hz_9 = QLabel(self.control_3)
        self.Hz_9.setObjectName(u"Hz_9")
        self.Hz_9.setGeometry(QRect(110, 50, 21, 16))
        self.du_47 = QLabel(self.control_3)
        self.du_47.setObjectName(u"du_47")
        self.du_47.setGeometry(QRect(250, 30, 21, 16))
        self.left_a_7 = QLabel(self.control_3)
        self.left_a_7.setObjectName(u"left_a_7")
        self.left_a_7.setGeometry(QRect(10, 10, 51, 16))
        self.send_desir = QPushButton(self.control_3)
        self.send_desir.setObjectName(u"send_desir")
        self.send_desir.setGeometry(QRect(160, 70, 80, 22))
        self.desir_pid = QLabel(self.control_3)
        self.desir_pid.setObjectName(u"desir_pid")
        self.desir_pid.setGeometry(QRect(170, 10, 41, 16))
        self.du_38 = QLabel(self.control_3)
        self.du_38.setObjectName(u"du_38")
        self.du_38.setGeometry(QRect(110, 280, 21, 16))
        self.du_39 = QLabel(self.control_3)
        self.du_39.setObjectName(u"du_39")
        self.du_39.setGeometry(QRect(130, 280, 21, 16))
        self.control_4 = QFrame(self.centralWidget)
        self.control_4.setObjectName(u"control_4")
        self.control_4.setGeometry(QRect(340, 450, 241, 221))
        self.control_4.setFrameShape(QFrame.StyledPanel)
        self.control_4.setFrameShadow(QFrame.Raised)
        self.MFAC = QLabel(self.control_4)
        self.MFAC.setObjectName(u"MFAC")
        self.MFAC.setGeometry(QRect(10, 10, 51, 16))
        self.yaw_pitch_depth = QLineEdit(self.control_4)
        self.yaw_pitch_depth.setObjectName(u"yaw_pitch_depth")
        self.yaw_pitch_depth.setGeometry(QRect(120, 30, 41, 16))
        self.left_p_11 = QLabel(self.control_4)
        self.left_p_11.setObjectName(u"left_p_11")
        self.left_p_11.setGeometry(QRect(10, 120, 61, 16))
        self.rou_2 = QLineEdit(self.control_4)
        self.rou_2.setObjectName(u"rou_2")
        self.rou_2.setGeometry(QRect(60, 180, 41, 16))
        self.left_a_9 = QLabel(self.control_4)
        self.left_a_9.setObjectName(u"left_a_9")
        self.left_a_9.setGeometry(QRect(10, 60, 51, 16))
        self.yita = QLineEdit(self.control_4)
        self.yita.setObjectName(u"yita")
        self.yita.setGeometry(QRect(60, 90, 41, 16))
        self.lambda0 = QLineEdit(self.control_4)
        self.lambda0.setObjectName(u"lambda")
        self.lambda0.setGeometry(QRect(60, 120, 41, 16))
        self.rightr_a_4 = QLabel(self.control_4)
        self.rightr_a_4.setObjectName(u"rightr_a_4")
        self.rightr_a_4.setGeometry(QRect(120, 90, 61, 16))
        self.leftr_p_4 = QLabel(self.control_4)
        self.leftr_p_4.setObjectName(u"leftr_p_4")
        self.leftr_p_4.setGeometry(QRect(10, 90, 51, 16))
        self.send_mfac = QPushButton(self.control_4)
        self.send_mfac.setObjectName(u"send_mfac")
        self.send_mfac.setGeometry(QRect(130, 180, 81, 23))
        self.left_k_4 = QLabel(self.control_4)
        self.left_k_4.setObjectName(u"left_k_4")
        self.left_k_4.setGeometry(QRect(10, 30, 101, 16))
        self.miu = QLineEdit(self.control_4)
        self.miu.setObjectName(u"miu")
        self.miu.setGeometry(QRect(60, 60, 41, 16))
        self.leftr_k_4 = QLabel(self.control_4)
        self.leftr_k_4.setObjectName(u"leftr_k_4")
        self.leftr_k_4.setGeometry(QRect(120, 60, 61, 16))
        self.left_p_12 = QLabel(self.control_4)
        self.left_p_12.setObjectName(u"left_p_12")
        self.left_p_12.setGeometry(QRect(10, 150, 61, 16))
        self.desir_pid_2 = QLabel(self.control_4)
        self.desir_pid_2.setObjectName(u"desir_pid_2")
        self.desir_pid_2.setGeometry(QRect(170, 10, 41, 16))
        self.rightr_a_5 = QLabel(self.control_4)
        self.rightr_a_5.setObjectName(u"rightr_a_5")
        self.rightr_a_5.setGeometry(QRect(120, 120, 61, 16))
        self.left_p_13 = QLabel(self.control_4)
        self.left_p_13.setObjectName(u"left_p_13")
        self.left_p_13.setGeometry(QRect(130, 150, 61, 16))
        self.left_p_14 = QLabel(self.control_4)
        self.left_p_14.setObjectName(u"left_p_14")
        self.left_p_14.setGeometry(QRect(10, 180, 61, 16))
        self.rou_1 = QLineEdit(self.control_4)
        self.rou_1.setObjectName(u"rou_1")
        self.rou_1.setGeometry(QRect(190, 150, 41, 16))
        self.rou_0 = QLineEdit(self.control_4)
        self.rou_0.setObjectName(u"rou_0")
        self.rou_0.setGeometry(QRect(60, 150, 41, 16))
        self.fai_init_0 = QLineEdit(self.control_4)
        self.fai_init_0.setObjectName(u"fai_init_0")
        self.fai_init_0.setGeometry(QRect(190, 60, 41, 16))
        self.fai_init_1 = QLineEdit(self.control_4)
        self.fai_init_1.setObjectName(u"fai_init_1")
        self.fai_init_1.setGeometry(QRect(190, 90, 41, 16))
        self.fai_init_2 = QLineEdit(self.control_4)
        self.fai_init_2.setObjectName(u"fai_init_2")
        self.fai_init_2.setGeometry(QRect(190, 120, 41, 16))
        self.control_5 = QFrame(self.centralWidget)
        self.control_5.setObjectName(u"control_5")
        self.control_5.setGeometry(QRect(30, 450, 271, 261))
        self.control_5.setFrameShape(QFrame.StyledPanel)
        self.control_5.setFrameShadow(QFrame.Raised)
        self.left_p_24 = QLabel(self.control_5)
        self.left_p_24.setObjectName(u"left_p_24")
        self.left_p_24.setGeometry(QRect(10, 30, 51, 16))
        self.yaw_kp = QLineEdit(self.control_5)
        self.yaw_kp.setObjectName(u"yaw_kp")
        self.yaw_kp.setGeometry(QRect(80, 30, 41, 16))
        self.yaw_kp.setToolTipDuration(-6)
        self.left_w_12 = QLabel(self.control_5)
        self.left_w_12.setObjectName(u"left_w_12")
        self.left_w_12.setGeometry(QRect(10, 90, 61, 16))
        self.left_p_25 = QLabel(self.control_5)
        self.left_p_25.setObjectName(u"left_p_25")
        self.left_p_25.setGeometry(QRect(10, 110, 61, 16))
        self.roll_ki = QLineEdit(self.control_5)
        self.roll_ki.setObjectName(u"roll_ki")
        self.roll_ki.setGeometry(QRect(80, 110, 41, 16))
        self.left_a_17 = QLabel(self.control_5)
        self.left_a_17.setObjectName(u"left_a_17")
        self.left_a_17.setGeometry(QRect(10, 70, 51, 16))
        self.yaw_kd = QLineEdit(self.control_5)
        self.yaw_kd.setObjectName(u"yaw_kd")
        self.yaw_kd.setGeometry(QRect(80, 70, 41, 16))
        self.roll_kp = QLineEdit(self.control_5)
        self.roll_kp.setObjectName(u"roll_kp")
        self.roll_kp.setGeometry(QRect(80, 90, 41, 16))
        self.pitch_kd = QLineEdit(self.control_5)
        self.pitch_kd.setObjectName(u"pitch_kd")
        self.pitch_kd.setGeometry(QRect(200, 70, 41, 16))
        self.rightr_a_10 = QLabel(self.control_5)
        self.rightr_a_10.setObjectName(u"rightr_a_10")
        self.rightr_a_10.setGeometry(QRect(140, 70, 51, 16))
        self.leftr_p_8 = QLabel(self.control_5)
        self.leftr_p_8.setObjectName(u"leftr_p_8")
        self.leftr_p_8.setGeometry(QRect(140, 30, 51, 16))
        self.pitch_kp = QLineEdit(self.control_5)
        self.pitch_kp.setObjectName(u"pitch_kp")
        self.pitch_kp.setGeometry(QRect(200, 30, 41, 16))
        self.send_pid = QPushButton(self.control_5)
        self.send_pid.setObjectName(u"send_pid")
        self.send_pid.setGeometry(QRect(160, 110, 81, 23))
        self.left_k_8 = QLabel(self.control_5)
        self.left_k_8.setObjectName(u"left_k_8")
        self.left_k_8.setGeometry(QRect(10, 50, 51, 16))
        self.yaw_ki = QLineEdit(self.control_5)
        self.yaw_ki.setObjectName(u"yaw_ki")
        self.yaw_ki.setGeometry(QRect(80, 50, 41, 16))
        self.pitch_ki = QLineEdit(self.control_5)
        self.pitch_ki.setObjectName(u"pitch_ki")
        self.pitch_ki.setGeometry(QRect(200, 50, 41, 16))
        self.leftr_k_8 = QLabel(self.control_5)
        self.leftr_k_8.setObjectName(u"leftr_k_8")
        self.leftr_k_8.setGeometry(QRect(140, 50, 51, 16))
        self.roll_kd = QLineEdit(self.control_5)
        self.roll_kd.setObjectName(u"roll_kd")
        self.roll_kd.setGeometry(QRect(80, 130, 41, 16))
        self.left_p_26 = QLabel(self.control_5)
        self.left_p_26.setObjectName(u"left_p_26")
        self.left_p_26.setGeometry(QRect(10, 130, 61, 16))
        self.desir_pid_6 = QLabel(self.control_5)
        self.desir_pid_6.setObjectName(u"desir_pid_6")
        self.desir_pid_6.setGeometry(QRect(170, 10, 41, 16))
        self.MFAC_3 = QLabel(self.control_5)
        self.MFAC_3.setObjectName(u"MFAC_3")
        self.MFAC_3.setGeometry(QRect(20, 10, 51, 16))
        self.left_p_27 = QLabel(self.control_5)
        self.left_p_27.setObjectName(u"left_p_27")
        self.left_p_27.setGeometry(QRect(10, 170, 61, 16))
        self.left_p_28 = QLabel(self.control_5)
        self.left_p_28.setObjectName(u"left_p_28")
        self.left_p_28.setGeometry(QRect(140, 170, 61, 16))
        self.left_p_29 = QLabel(self.control_5)
        self.left_p_29.setObjectName(u"left_p_29")
        self.left_p_29.setGeometry(QRect(10, 190, 61, 16))
        self.left_p_30 = QLabel(self.control_5)
        self.left_p_30.setObjectName(u"left_p_30")
        self.left_p_30.setGeometry(QRect(140, 190, 61, 16))
        self.left_base = QLineEdit(self.control_5)
        self.left_base.setObjectName(u"left_base")
        self.left_base.setGeometry(QRect(70, 170, 41, 16))
        self.left_roll = QLineEdit(self.control_5)
        self.left_roll.setObjectName(u"left_roll")
        self.left_roll.setGeometry(QRect(70, 190, 41, 16))
        self.pitch = QLineEdit(self.control_5)
        self.pitch.setObjectName(u"pitch")
        self.pitch.setGeometry(QRect(70, 210, 41, 16))
        self.left_k_2 = QLineEdit(self.control_5)
        self.left_k_2.setObjectName(u"left_k_2")
        self.left_k_2.setGeometry(QRect(200, 210, 41, 16))
        self.right_base = QLineEdit(self.control_5)
        self.right_base.setObjectName(u"right_base")
        self.right_base.setGeometry(QRect(200, 170, 41, 16))
        self.right_roll = QLineEdit(self.control_5)
        self.right_roll.setObjectName(u"right_roll")
        self.right_roll.setGeometry(QRect(200, 190, 41, 16))
        self.right_k = QLineEdit(self.control_5)
        self.right_k.setObjectName(u"right_k")
        self.right_k.setGeometry(QRect(70, 230, 41, 16))
        self.left_p_31 = QLabel(self.control_5)
        self.left_p_31.setObjectName(u"left_p_31")
        self.left_p_31.setGeometry(QRect(10, 210, 61, 16))
        self.left_p_33 = QLabel(self.control_5)
        self.left_p_33.setObjectName(u"left_p_33")
        self.left_p_33.setGeometry(QRect(140, 210, 61, 16))
        self.left_p_34 = QLabel(self.control_5)
        self.left_p_34.setObjectName(u"left_p_34")
        self.left_p_34.setGeometry(QRect(10, 230, 61, 16))
        self.du_40 = QLabel(self.control_5)
        self.du_40.setObjectName(u"du_40")
        self.du_40.setGeometry(QRect(120, 170, 21, 16))
        self.du_41 = QLabel(self.control_5)
        self.du_41.setObjectName(u"du_41")
        self.du_41.setGeometry(QRect(250, 170, 21, 16))
        self.du_42 = QLabel(self.control_5)
        self.du_42.setObjectName(u"du_42")
        self.du_42.setGeometry(QRect(250, 190, 21, 16))
        self.du_43 = QLabel(self.control_5)
        self.du_43.setObjectName(u"du_43")
        self.du_43.setGeometry(QRect(120, 190, 21, 16))
        self.du_44 = QLabel(self.control_5)
        self.du_44.setObjectName(u"du_44")
        self.du_44.setGeometry(QRect(120, 210, 21, 16))
        self.du_46 = QLabel(self.control_5)
        self.du_46.setObjectName(u"du_46")
        self.du_46.setGeometry(QRect(250, 210, 21, 16))
        self.du_48 = QLabel(self.control_5)
        self.du_48.setObjectName(u"du_48")
        self.du_48.setGeometry(QRect(120, 230, 21, 16))
        self.send_base = QPushButton(self.control_5)
        self.send_base.setObjectName(u"send_base")
        self.send_base.setGeometry(QRect(160, 230, 81, 23))
        MainWindow.setCentralWidget(self.centralWidget)
        self.mainToolBar = QToolBar(MainWindow)
        self.mainToolBar.setObjectName(u"mainToolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"Close", None))
        self.du_4.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Yaw.setText(QCoreApplication.translate("MainWindow", u"Yaw", None))
        self.mi.setText(QCoreApplication.translate("MainWindow", u"cm", None))
        self.Yaw_s.setText(QCoreApplication.translate("MainWindow", u"-180.0", None))
        self.Roll.setText(QCoreApplication.translate("MainWindow", u"Roll", None))
        self.du_2.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Roll_s.setText(QCoreApplication.translate("MainWindow", u"050.0", None))
        self.Pitch.setText(QCoreApplication.translate("MainWindow", u"Pitch", None))
        self.Pitch_s.setText(QCoreApplication.translate("MainWindow", u"090.0", None))
        self.du_3.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Depth.setText(QCoreApplication.translate("MainWindow", u"Depth", None))
        self.Depth_s.setText(QCoreApplication.translate("MainWindow", u"10.22", None))
        self.Led_gps.setText(QCoreApplication.translate("MainWindow", u"Led_gps", None))
        self.Led_star.setText(QCoreApplication.translate("MainWindow", u"Led_star", None))
        self.Led_star_s.setText("")
        self.Led_gps_s.setText("")
        self.left_w.setText(QCoreApplication.translate("MainWindow", u"left_w", None))
        self.left_a.setText(QCoreApplication.translate("MainWindow", u"left_a", None))
        self.left_p.setText(QCoreApplication.translate("MainWindow", u"left_p", None))
        self.left_a_s.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.left_w_s.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.left_p_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_w_2.setText(QCoreApplication.translate("MainWindow", u"right_w", None))
        self.left_p_2.setText(QCoreApplication.translate("MainWindow", u"right_p", None))
        self.right_p_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_a_2.setText(QCoreApplication.translate("MainWindow", u"right_a", None))
        self.right_a_s.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.right_w_s.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.rightr_p.setText(QCoreApplication.translate("MainWindow", u"rightr_p", None))
        self.rightr_a_s.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.rightr_p_s.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.rightr_w_s.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.rightr_w.setText(QCoreApplication.translate("MainWindow", u"rightr_w", None))
        self.rightr_a.setText(QCoreApplication.translate("MainWindow", u"rightr_a", None))
        self.leftr_w.setText(QCoreApplication.translate("MainWindow", u"leftr_w", None))
        self.leftr_p.setText(QCoreApplication.translate("MainWindow", u"leftr_p", None))
        self.leftr_p_s.setText(QCoreApplication.translate("MainWindow", u"90", None))
        self.leftr_a.setText(QCoreApplication.translate("MainWindow", u"leftr_a", None))
        self.leftr_a_s.setText(QCoreApplication.translate("MainWindow", u"20", None))
        self.leftr_w_s.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.rightt_a.setText(QCoreApplication.translate("MainWindow", u"rightt_a", None))
        self.rightt_a_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.leftt_a_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.leftt_a.setText(QCoreApplication.translate("MainWindow", u"leftt_a", None))
        self.back_a_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.back.setText(QCoreApplication.translate("MainWindow", u"back_a", None))
        self.du_7.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Hz.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.du_9.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Hz_2.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.du_8.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_10.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_11.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_12.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Hz_3.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.du_15.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_16.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_17.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_13.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_14.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Hz_4.setText(QCoreApplication.translate("MainWindow", u"Hz", None))
        self.run_no.setText(QCoreApplication.translate("MainWindow", u"run_no", None))
        self.run_no_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.Led_gps_2.setText(QCoreApplication.translate("MainWindow", u"Led_gps", None))
        self.Led_forward.setText(QCoreApplication.translate("MainWindow", u"Led_forward", None))
        self.Led_star_s_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.Led_gps_s_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_k.setText(QCoreApplication.translate("MainWindow", u"left_k", None))
        self.left_k_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.du_18.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_19.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.leftr_k_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.leftr_k.setText(QCoreApplication.translate("MainWindow", u"leftr_k", None))
        self.du_20.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.rightr_k_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.rightr_k.setText(QCoreApplication.translate("MainWindow", u"rightr_k", None))
        self.du_21.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.right_k_s.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_p_3.setText(QCoreApplication.translate("MainWindow", u"right_k", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"SEND", None))
        self.left_w_5.setText(QCoreApplication.translate("MainWindow", u"depth", None))
        self.left_a_5.setText(QCoreApplication.translate("MainWindow", u"yaw", None))
        self.yaw_desire.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.roll_desire.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.leftr_w_3.setText(QCoreApplication.translate("MainWindow", u"RUN_NO", None))
        self.leftr_a_3.setText(QCoreApplication.translate("MainWindow", u"pitch", None))
        self.pitch_desire.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.run_or_on_pid.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.du_37.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.Hz_9.setText(QCoreApplication.translate("MainWindow", u"m", None))
        self.du_47.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.left_a_7.setText(QCoreApplication.translate("MainWindow", u"Desir", None))
        self.send_desir.setText(QCoreApplication.translate("MainWindow", u"SEND", None))
        self.desir_pid.setText("")
        self.du_38.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_39.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.MFAC.setText(QCoreApplication.translate("MainWindow", u"MFAC", None))
        self.yaw_pitch_depth.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_p_11.setText(QCoreApplication.translate("MainWindow", u"lambda0", None))
        self.rou_2.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.left_a_9.setText(QCoreApplication.translate("MainWindow", u"miu", None))
        self.yita.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.lambda0.setText(QCoreApplication.translate("MainWindow", u"0.05", None))
        self.rightr_a_4.setText(QCoreApplication.translate("MainWindow", u"fai_init[1]", None))
        self.leftr_p_4.setText(QCoreApplication.translate("MainWindow", u"yita", None))
        self.send_mfac.setText(QCoreApplication.translate("MainWindow", u"SEND_MFAC", None))
        self.left_k_4.setText(QCoreApplication.translate("MainWindow", u"yaw_pitch_roll", None))
        self.miu.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.leftr_k_4.setText(QCoreApplication.translate("MainWindow", u"fai_init[0]", None))
        self.left_p_12.setText(QCoreApplication.translate("MainWindow", u"rou[0]", None))
        self.desir_pid_2.setText("")
        self.rightr_a_5.setText(QCoreApplication.translate("MainWindow", u"fai_init[2]", None))
        self.left_p_13.setText(QCoreApplication.translate("MainWindow", u"rou[1]", None))
        self.left_p_14.setText(QCoreApplication.translate("MainWindow", u"rou[2]", None))
        self.rou_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.rou_0.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.fai_init_0.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.fai_init_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.fai_init_2.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.left_p_24.setText(QCoreApplication.translate("MainWindow", u"yaw_kp", None))
        self.yaw_kp.setText(QCoreApplication.translate("MainWindow", u"0.1", None))
        self.left_w_12.setText(QCoreApplication.translate("MainWindow", u"depthl_kp", None))
        self.left_p_25.setText(QCoreApplication.translate("MainWindow", u"depth_ki", None))
        self.roll_ki.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_a_17.setText(QCoreApplication.translate("MainWindow", u"yaw_kd", None))
        self.yaw_kd.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.roll_kp.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pitch_kd.setText(QCoreApplication.translate("MainWindow", u"0.1", None))
        self.rightr_a_10.setText(QCoreApplication.translate("MainWindow", u"pitch_kd", None))
        self.leftr_p_8.setText(QCoreApplication.translate("MainWindow", u"pitch_kp", None))
        self.pitch_kp.setText(QCoreApplication.translate("MainWindow", u"10", None))
        self.send_pid.setText(QCoreApplication.translate("MainWindow", u"SEND_PID", None))
        self.left_k_8.setText(QCoreApplication.translate("MainWindow", u"yaw_ki", None))
        self.yaw_ki.setText(QCoreApplication.translate("MainWindow", u"0.5", None))
        self.pitch_ki.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.leftr_k_8.setText(QCoreApplication.translate("MainWindow", u"pitch_ki", None))
        self.roll_kd.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_p_26.setText(QCoreApplication.translate("MainWindow", u"depth_kd", None))
        self.desir_pid_6.setText("")
        self.MFAC_3.setText(QCoreApplication.translate("MainWindow", u"PID", None))
        self.left_p_27.setText(QCoreApplication.translate("MainWindow", u"left", None))
        self.left_p_28.setText(QCoreApplication.translate("MainWindow", u"right", None))
        self.left_p_29.setText(QCoreApplication.translate("MainWindow", u"left_roll", None))
        self.left_p_30.setText(QCoreApplication.translate("MainWindow", u"right_roll", None))
        self.left_base.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.left_roll.setText(QCoreApplication.translate("MainWindow", u"30", None))
        self.pitch.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.left_k_2.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.right_base.setText(QCoreApplication.translate("MainWindow", u"15", None))
        self.right_roll.setText(QCoreApplication.translate("MainWindow", u"27", None))
        self.right_k.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.left_p_31.setText(QCoreApplication.translate("MainWindow", u"pitch", None))
        self.left_p_33.setText(QCoreApplication.translate("MainWindow", u"left_k", None))
        self.left_p_34.setText(QCoreApplication.translate("MainWindow", u"right_k", None))
        self.du_40.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_41.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_42.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_43.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_44.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_46.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.du_48.setText(QCoreApplication.translate("MainWindow", u"\u00b0", None))
        self.send_base.setText(QCoreApplication.translate("MainWindow", u"SEND_BASE", None))
    # retranslateUi

